### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kevinluolk** [stefpeschel/NetCoMi#48] opened 2022-04-09 16:39 UTC
Hi Stefanie, 
I met a problem while installing NetCoMi as shown below. Are there any suggestions to solve this error? 

Thank you so much. 

Kai 

 devtools::install_github("stefpeschel/NetCoMi",  
+                          dependencies = c("Depends", "Imports"),
+                          repos = c("https://cloud.r-project.org/",
+                                    BiocManager::repositories()))
_Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 47.19.177.245. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2022-04-09 17:12:55 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`._

**Comment by stefpeschel** [comment] 2022-04-13 11:05
Hey Kai,
Since you also wrote me an email that the issue is solved, I'd close this issue now. 
Best,
Stefanie

**Closed by stefpeschel** 2022-04-13 11:05 UTC

**Comment by eknorr1** [comment] 2022-05-13 05:17
Hi I am having the same error, I was wondering what the solution was?
