### ISSUE TITLE
Error in .checkArgsPlotHeat(argsIn) : "mat" must be a numeric matrix

### ISSUE THREAD

**Issue by Dirrrrty** [stefpeschel/NetCoMi#93] opened 2023-08-29 06:22 UTC
Hello :)
I am running through the tutorial for network comparison and I manage to run the netconstruct command but then when I try to proceeed to run netanalyze i keep getting a warning that suggests that my network matrix is not a matrix? How can I rectify this or what should I be checking in the code to avoid this.
Thanks

**Comment by stefpeschel** [comment] 2023-08-31 15:34
Hey, 

This error is produced by the function for plotting the graphlet correlation matrix. So, something seems to be wrong with this matrix. 

Could you please try setting the argument `gcmHeat` to `FALSE` and see if the function runs without errors?

To find the cause of this issue, some more information about your code would be helpful. Could you please provide me with the code that produces this error? And what type of data are you using (data matrix or phyloseq object)?
Thanks a lot.

**Comment by stefpeschel** [comment] 2023-10-10 21:08
I will close this issue now. Please reopen it if the error persists.

**Closed by stefpeschel** 2023-10-10 21:08 UTC
